{% set name = "xmle" %}
{% set version = "0.1.22" %}
{% set checksum = "e745baebdd09c05678096be5d831824e7dd8ca4ed632bdb14863af4880aeadfb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpn--/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas

test:
  imports:
    - xmle

about:
  home: https://github.com/jpn--/xmle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xml extension for generating neatly formatted HTML output from a variety of object types
  dev_url: https://github.com/jpn--/xmle

extra:
  recipe-maintainers:
    - jpn--
