{% set name = "xmle" %}
{% set version = "0.1.27" %}
{% set checksum = "03a29c8aae7bca0852b1491be8540f24742944acf7798a87d919980935607e25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpn--/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - xmle

about:
  home: https://github.com/jpn--/xmle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xml extension for generating neatly formatted HTML output from a variety of object types
  dev_url: https://github.com/jpn--/xmle

extra:
  recipe-maintainers:
    - jpn--
