{% set name = "xmle" %}
{% set version = "0.1.26" %}
{% set checksum = "776442d84777b6fd793a699a588b721a664404812d81dd3bfcdf67276c24d0eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpn--/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pandas

test:
  imports:
    - xmle

about:
  home: https://github.com/jpn--/xmle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xml extension for generating neatly formatted HTML output from a variety of object types
  dev_url: https://github.com/jpn--/xmle

extra:
  recipe-maintainers:
    - jpn--
