{% set name = "xmle" %}
{% set version = "0.1.24" %}
{% set checksum = "b557c041afef38060de6dcd90f2f5fb205572be51a28df7bde82dce0fd101fc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jpn--/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas

test:
  imports:
    - xmle

about:
  home: https://github.com/jpn--/xmle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: xml extension for generating neatly formatted HTML output from a variety of object types
  dev_url: https://github.com/jpn--/xmle

extra:
  recipe-maintainers:
    - jpn--
